snakeoil/blueprints/admin/views.py
from flask import Blueprint, render_template
from flask_login import login_required

from snakeoil.blueprints.user.models import User
from snakeoil.blueprints.product.models import Product
from snakeoil.blueprints.purchase.models import Purchase
from snakeoil.blueprints.admin.decorators import role_required

admin = Blueprint("admin", __name__,
                  template_folder="templates", url_prefix="/admin")


@admin.before_request
@login_required
@role_required("admin")
def before_request():
    """ Protect all admin routes """
    pass


@admin.route("", methods=["GET"])
def index():
    """
    Display high level counts
    """
    context = {
        "products": Product.query.count(),
        "purchases": Purchase.query.count(),
        "users": User.query.count(),
    }
    return render_template("admin/index.html", context=context)


@admin.route("/sales")
def sales():
    context = {
        "purchases": Purchase.query.order_by(
            Purchase.created_at.desc()).limit(50),
    }
    return render_template("admin/sales.html", context=context)


@admin.route("/products")
def products():
    context = {
        "products": Product.query.all(),
    }
    return render_template("admin/products.html", context=context)


@admin.route("/users")
def users():
    context = {
        "users": User.query.all(),
    }
    return render_template("admin/users.html", context=context)

snakeoil/blueprints/user/views.py
from flask import (
    Blueprint,
    request,
    render_template,
    flash,
    redirect,
    url_for,
)

from flask_login import login_user, logout_user

from lib.safe_next_url import safe_next_url
from snakeoil.blueprints.user.models import User
from snakeoil.blueprints.admin.decorators import anonymous_required
from snakeoil.blueprints.user.forms import (
    LoginForm,
    RegistrationForm,
    PasswordForgotForm,
    PasswordResetForm,
)

user = Blueprint("user", __name__, template_folder="templates")


@user.route("/login", methods=["GET", "POST"])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get("next"))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Invalid email or password")
            return redirect(url_for("user.login"))
        login_user(user, remember=True)
        next_url = request.form.get("next")
        if next_url:
            return redirect(safe_next_url(next_url))
        return redirect(url_for("product.index"))
    return render_template("user/login.html", form=form)


@user.route("/register", methods=["GET", "POST"])
@anonymous_required()
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data)
        user.set_password(form.password.data)
        user.save()
        flash("Success! Thanks for signing up!")
        return redirect(url_for("user.login"))
    return render_template("user/register.html", form=form)


@user.route("/forgot-password", methods=["GET", "POST"])
@anonymous_required()
def forgot_password():
    form = PasswordForgotForm()
    if form.validate_on_submit():
        User.initialized_password_reset(request.form.get("email"))
        flash("A password reset link has been sent to your email")
        return redirect(url_for("user.login"))
    return render_template("user/forgot.html", form=form)


@user.route("/reset-password", methods=["GET", "POST"])
@anonymous_required()
def reset_password():
    form = PasswordResetForm(reset_token=request.args.get("reset_token"))

    if form.validate_on_submit():
        user = User.deserialize_token(request.form.get("reset_token"))

        if user is None:
            flash("Your reset password reset link has expired")
            return redirect(url_for("user.forgot_password"))

        user.password_hash = User.encrypt_password(
            request.form.get("password"))
        user.save()

        if login_user(user):
            flash("Your password has been reset")
            return redirect(url_for("product.index"))

    return render_template("user/reset.html", form=form)


@user.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("product.index"))

snakeoil/templates/partials/admin-nav.html
<div class="wrap-dashboard-menu pad">
  <h5 class="nav-title">NAVIGATION</h5>
  <div class="menu-link {% if active_page == 'dashboard' %}active{% endif %}">
    <div data-icon="ei-chart" class="menu-icon"></div>
    <a href="{{ url_for('admin.index') }}">Overview</a>
  </div>
  <div class="menu-link {% if active_page == 'sales' %}active{% endif %}">
    <div data-icon="ei-credit-card" class="menu-icon"></div>
    <a href="{{ url_for('admin.sales') }}">Sales</a>
  </div>
  <div class="menu-link {% if active_page == 'products' %}active{% endif %}">
    <div data-icon="ei-archive" class="menu-icon"></div>
    <a href="{{ url_for('admin.products') }}">Products</a>
  </div>
  <div class="menu-link {% if active_page == 'users' %}active{% endif %}">
    <div data-icon="ei-user" class="menu-icon"></div>
    <a href="{{ url_for('admin.users') }}">Users</a>
  </div>
</div>

snakeoil/templates/partials/messages.html
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class="flash-container pad">
      <ul>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}
{% endwith %}

snakeoil/templates/partials/nav.html
<header>
  <div class="logo-container">
    <h2 class="title"><a href="{{ url_for('product.index') }}">The Wealthy Earth</a></h2>
  </div>
  {% if current_user.is_authenticated %}
    <div class="nav-container">
      <div class="link"><a href="{{ url_for('user.logout') }}">Logout</a></div>
      {% if current_user.role == 'admin' %}
        <div class="link"><a href="{{ url_for('admin.index') }}">Admin</a></div>
      {% endif %}
    </div>
  {% else %}
    <div class="nav-container">
      <div class="link"><a href="{{ url_for('user.login') }}">Login</a></div>
      <div class="link"><a href="{{ url_for('user.register') }}">Register</a></div>
    </div>
  {% endif %}
</header>