snakeoil/blueprints/product/models.py
from collections import OrderedDict

from snakeoil.extensions import db


class Product(db.Model):
    TYPE = OrderedDict(
        [
            ("pdf", "PDF"),
            ("video", "Video"),
        ]
    )

    __tablename__ = "products"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    file_name = db.Column(db.String)
    version = db.Column(db.String)
    is_active = db.Column(db.Boolean, default=True)
    price = db.Column(db.Float)
    thumbnail_url = db.Column(db.String(255))
    banner_url = db.Column(db.String(255))
    description_short = db.Column(db.String(255))
    description_long = db.Column(db.Text)
    product_type = db.Column(
        db.Enum(*TYPE, name="product_types", native_enum=False))

    def __repr__(self):
        return "<Product {}>".format(self.name)

snakeoil/blueprints/product/__init__.py
from snakeoil.blueprints.product.views import product

snakeoil/blueprints/product/views.py
from flask import Blueprint, render_template, current_app

from snakeoil.blueprints.product.models import Product

product = Blueprint("product", __name__, template_folder="templates")


@product.route("/", methods=["GET"])
@product.route("/products", methods=["GET"])
def index():
    context = {}
    context["products"] = Product.query.filter_by(is_active=True).all()
    return render_template("product/index.html", context=context)


@product.route("/products/<int:id>", methods=["GET"])
def show(id):
    context = {}
    product = Product.query.filter_by(id=id).first_or_404()
    context["product"] = product
    context["stripe_key"] = current_app.config.get("STRIPE_PUBLISHABLE_KEY")
    return render_template("product/show.html", context=context)

snakeoil/blueprints/product/templates/product/index.html
{% extends "layouts/base.html" %}

{% block header %}
  {% include "partials/nav.html" %}
{% endblock header %}

{% block content %}
  <div class="container">
    <div class="product-grid">
      {% for product in context.products %}
        <a href="{{ url_for('product.show', id=product.id) }}" class="product-card">
          <img src="{{ url_for('static', filename=product.thumbnail_url) }}">
          <div class="product-details">
            <div class="product-details__info">
              <h4 class="title">{{ product.name }}</h4>
              <p class="description">{{ product.description_short }}</p>
            </div>
            <div class="product-details__pricing">
              <div class="product-pricing">
                <span class="symbol-dollar">$</span>
                <span class="price">{{ "{:,.2f}".format(product.price) }}</span>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

snakeoil/blueprints/product/templates/product/partials/composting-desc.html
<div class="product-info">
  <h2 class="product-title push-half--bottom">Description</h2>
  <p class="product-description push--bottom">
    This 75 minute class walks you through the way of making a premier soil additive with material coming from your kitchen and yard.
    You’ll learn what ingredients to add and what to avoid. You’ll learn about nitrogen and carbon, along with the 4 “M’s” of making a
    great batch of compost in as little as six weeks. The balance of green and brown materials along with the science of composting are
    all discussed. Done correctly, this will be the only fertilizer you’ll ever need for your gardens. There’s a reason why they call
    it “black gold” and you’ll be wondering why you haven’t been doing it for years. Like many things in life, you can never beat homemade.
    Thats certainly true with making your own compost. You’ll never buy it as good as you can make it.
  </p>
</div>

snakeoil/blueprints/product/templates/product/partials/hot-weather-lettuce-desc.html
<div class="product-info">
  <h2 class="product-title push-half--bottom">Description</h2>
  <p class="product-description push--bottom">
    If you live in a location where summer temperatures get higher than 80 degrees, you’ll know the challenge of trying to grow
    lettuce during this period. If you live in an area where you have protracted summer heat its even more difficult. Lettuce
    seeds are practically impossible to germinate in temps over 80. What good is having vine-ripened tomatoes, home grown onions
    and cucumbers if you can’t have fresh lettuce? This book takes you through the 5 steps to successfully have and harvest lettuce
    right thought extreme summer heat. In northern Utah, we’ve had temperatures of 95-104 for 5 weeks straight. Yet, I’ve been able
    to harvest a steady supply of lettuce greens all summer long. Once you learn the tricks you’ll be having the best tasting,
    freshly harvested salad greens that only the best restaurants in the country serve. You’ll never be satisfied buying at the
    grocery store when you learn how to do it.
  </p>
</div>

snakeoil/blueprints/product/templates/product/partials/low-tunnel-gardening.html
<div class="product-info">
  <h2 class="product-title push-half--bottom">Description</h2>
  <p class="product-description push--bottom">
    A short discussion on greenhouses and high tunnels before learning about low
    tunnels, which are amazing when you see what’s possible in even the harshest
    of climates. This class is 2-1/2 hours long and takes you down the journey of
    setting up and building your tunnels for a growing experience you’ve never
    had before. We discuss 4 different options for choosing the best tunnel for
    you. It’s seventeen degrees outside with a wind chill factor of minus 4? No
    problem! The final part of class are the crops you can grow and a planting
    schedule guide. This is a very content rich class.
  </p>
</div>

snakeoil/blueprints/product/templates/product/partials/seed-starting-desc.html
<div class="product-info push--top">
  <h2 class="product-title push-half--bottom">Description</h2>
  <p class="product-description push--bottom">
    This 90 minute class takes you from beginning to end in learning how to successfully start your own crops,
    whether they be your favorite flowers or vegetables. A quick discussion about seeds, the right medium to grow in,
    different containers to use, and then we finish by showing you how to make your own light station.
  </p>
</div>

snakeoil/blueprints/product/templates/product/partials/sfg-101-desc.html
<div class="product-info">
  <h2 class="product-title push-half--bottom">Description</h2>
  <p class="product-description push--bottom">
    Ultricies integer quis auctor elit sed vulputate mi sit amet. Leo duis ut
    diam quam nulla porttitor massa id. Egestas egestas fringilla phasellus
    faucibus scelerisque eleifend donec pretium vulputate. Ut tortor pretium
    viverra suspendisse potenti nullam ac tortor. Tellus at urna condimentum
    mattis pellentesque id. Nunc congue nisi vitae suscipit tellus mauris.
    Consequat mauris nunc congue nisi vitae suscipit. Sit amet consectetur
    adipiscing elit duis tristique sollicitudin nibh sit. Eu turpis egestas
    pretium aenean pharetra magna ac. Ut tristique et egestas quis ipsum
    suspendisse ultrices gravida dictum. Turpis egestas maecenas pharetra
    convallis posuere morbi. Vivamus arcu felis bibendum ut. A diam
    sollicitudin tempor id eu nisl nunc. Dui id ornare arcu odio ut sem
    nulla. Dui sapien eget mi proin sed libero enim. Tincidunt tortor aliquam
    nulla facilisi. Velit ut tortor pretium viverra suspendisse potenti
    nullam. Tincidunt dui ut ornare lectus sit amet est placerat. Venenatis
    urna cursus eget nunc.
  </p>
  <p class="product-description push--bottom">
    Ultricies integer quis auctor elit sed vulputate mi sit amet. Leo duis ut
    diam quam nulla porttitor massa id. Egestas egestas fringilla phasellus
    Ultricies integer quis auctor elit sed vulputate mi sit amet. Leo duis ut
    diam quam nulla porttitor massa id. Egestas egestas fringilla phasellus
  </p>
</div>

snakeoil/blueprints/product/templates/product/partials/wealthy-earth-101-desc.html
<div class="product-info">
  <h2 class="product-title push-half--bottom">Description</h2>
  <p class="product-description push--bottom">
    An organic method to save 90% of your water. Save 95% of your seeds the first year. Garden in only 20% of the space of a traditional garden yet enjoy 100% of the harvest.
    This one hour and twenty minute class teaches you the basics of using a weed barrier, building a box, the importance of Mel’s mix and the grid, and the plant spacings.
    You’ll see why we don’t weed and why we use a lot less water than a traditional garden. Square foot gardening is the best and easiest way to grow the best food ever.
    Learn how to make gardening fun again.
  </p>
</div>

snakeoil/blueprints/product/templates/product/show.html
{% extends "layouts/base.html" %}

{% block header %}
  {% include "partials/nav.html" %}
{% endblock header %}

{% block content %}
  <div
    class="product-header"
    style="background: linear-gradient(rgba(0, 184, 148, 0.85), rgba(0, 184, 148, 0.85)), url({{ url_for('static', filename=context.product.banner_url) }});"
  >
    <div class="container">
      <h2 class="title">{{ context.product.name }}</h2>
      <h6 class="short-description">{{ context.product.description_short }}</h6>
      <button class="btn btn-sm btn-stripe">Buy now for ${{ "{:,.2f}".format(context.product.price) }}</button>
    </div>
  </div>
  <div class="container pad--ends">
    <div class="product-info">
      {% if context.product.id == 1 %}
        {% include "product/partials/sfg-101-desc.html" %}
      {% elif context.product.id == 2 %}
        {% include "product/partials/hot-weather-lettuce-desc.html" %}
      {% elif context.product.id == 3 %}
        {% include "product/partials/composting-desc.html" %}
      {% elif context.product.id == 4 %}
        {% include "product/partials/seed-starting-desc.html" %}
      {% elif context.product.id == 5 %}
        {% include "product/partials/low-tunnel-gardening.html" %}
      {% elif context.product.id == 6 %}
        {% include "product/partials/wealthy-earth-101-desc.html" %}
      {% endif %}
    </div>

    <section class="section vertical-space-extra">
      <div class="grid-3">
        <div class="marketing-card">
          <div class="head">
            <img src="{{ url_for('static', filename='assets/img/tools@2x.png') }}" alt="tools" class="icon icon-tools">
            <h4 class="title">An efficient gardening system</h4>
          </div>
          <p class="content">
            The Square Foot Gardening system was designed to produce just as much (or more)
            than a traditional garden even in small spaces.
          </p>
        </div>
        <div class="marketing-card">
          <div class="head">
            <img src="{{ url_for('static', filename='assets/img/glove@2x.png') }}" alt="glove" class="icon icon-glove">
            <h4 class="title">Easy and fun</h4>
          </div>
          <p class="content">
            Square Foot Gardening claims an 80% reduction in water, garden size, weeding, and overall garden work.
            Here you’ll learn all those tips and tricks so you can focus on growing plants you love!
          </p>
        </div>
        <div class="marketing-card">
          <div class="head">
            <img src="{{ url_for('static', filename='assets/img/plant@2x.png') }}" alt="plant" class="icon icon-plant">
            <h4 class="title">Effective for anyone</h4>
          </div>
          <p class="content">
            Along with a wealth of Square Foot Gardening observations and advice,
            the author has included some of his family's favorite recipes.
          </p>
        </div>
      </div>
    </section>

    <section class="section">
      <div class="text--center">
        <button id="custom" class="btn btn-stripe primary btn-lg">Buy now for ${{ "{:,.2f}".format(context.product.price) }}</button>
      </div>
    </section>
  </div>
{% endblock content %}

{% block extrascripts %}
  <script>
    const purchaseBtns = document.querySelectorAll('.btn-stripe');
    const productPrice = parseFloat('{{ context.product.price * 100 }}');

    const formatJson = response => response.json();
    const handleSuccess = response => window.location = response.redirectURI;
    const handleError = error => {
      const toastConfig = {
        text: 'There was an error trying to complete your order',
        duration: 3000,
        close: true,
        gravity: 'top',
        positionLeft: false,
        backgroundColor: '#d63031',
      };

      Toastify(toastConfig).showToast();
    };

    const handler = StripeCheckout.configure({
      key: '{{ context.stripe_key }}',
      image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
      locale: 'auto',
      zipCode: true,
      token: function(token) {
        const { id, email } = token;
        fetch('/charge', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            email,
            token: id,
            productId: '{{ context.product.id }}',
          }),
        })
          .then(formatJson)
          .then(handleSuccess)
          .catch(handleError);
      }
    });

    function addStripeListener(btn) {
      btn.addEventListener('click', function(e) {
        e.preventDefault();
        handler.open({
          name: '{{ context.product.name }}',
          description: '{{ context.product.product_type|upper }}',
          amount: productPrice,
        });
      });
    }

    purchaseBtns.forEach(addStripeListener);

    window.addEventListener('popstate', function() {
      handler.close();
    });
  </script>
{% endblock extrascripts %}